### ISSUE TITLE
Login fails

### ISSUE THREAD

**Issue by chrismarquardt** [davidfokkema/fix-canon-name#1]
Here's the source of my LBP622C/623C printer's login page.

While your script asks only for a PIN, here the login page requires a system manager ID and a PIN in order to change any network settings, such as the Airprint Name.

Providing a Remote UI Access PIN (also asked for on this page) is not sufficient, as that will not have the rights to change network settings. 

Update: Turns out pasting HTML in an issue tries to render it. I'll attach the sources as a file instead

**Comment by chrismarquardt** [comment]
[pages.txt](https://github.com/davidfokkema/fix-canon-name/files/15416148/pages.txt)

**Comment by davidfokkema** [comment]
Thanks for the source! I was a bit surprised to see the login page has additional fields for admin id/pin since I've got the same printer (LBP623Cdw). It turns out that you can enable/disable separate login for administrators via settings -> user management -> system manager information -> edit -> enable/disable the checkbox marked "Set ID and PIN". If you disable that checkbox the 'normal' remote UI PIN should be able to change the network name and the app works as expected.

Do you need (or want) that separate login for administrators? If so, I'll add that to the app, no problem.

**Comment by chrismarquardt** [comment]
Ah I see. Not sure why that's switched on in my printer. I should be able to operate without the separate system manager settings. Thanks for pointing that out.

**Comment by davidfokkema** [comment]
Great! Then I'll close this issue for now. If there's anything else, please let me know.
